In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [21]:
import tensorflow as tf
from tensorflow.keras.models import Model
# from tensorflow.keras.layers import Input, Dense, Embedding, Flatten, Concatenate, Normalization
from tensorflow.keras import Input
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder
from sklearn.base import BaseEstimator, TransformerMixin
import copy



In [6]:
class EmbeddingGenerator(BaseEstimator, TransformerMixin):
    def __init__(self, epochs=5, batch_size=128, embedding_size=None):
        self.model = None
        self.catagorical_columns = []
        self.numberical_columns = []
        self.epochs = epochs
        self.batch_size = batch_size
        self.embedding_size = embedding_size
        self.oe = OrdinalEncoder(categories="auto", handle_unknown="use_encoded_value", unknown_value=9999, encoded_missing_value=9999, dtype=np.int32)
        #encode category by number
    def fit(self, X_train, y_train):
        self.X_train = X_train
        self._get_encoded_categorical_data(X_train)
        self._get_numerical_data(X_train)


    def _get_encoded_categorical_data(self, X, case='train'):
        self.cateegorical_columns = X.select_dtype(include=['object', 'category']).columns.tolist() #select column that is type of include
        self.n_categories = [X[c].unique() for c in self.cateegorical_columns] #how many level in each categorical column
        if case == 'train':
            encoded_cat_data = self.oe.fit_transform(X[self.catagorical_columns]) #2d array
        if case=='predict':
            encoded_cat_data = self.oe.transform(X[self.catagorical_columns]) #2d array
        return [encoded_cat_data[:,i] for i in range(encoded_cat_data.shape[1])] #encoded_cat_data.shape[1] is number of columns
    #return a list of 1d array
    """[array([941, 941, 941, ...,   0,   0,   0], dtype=int32),
   array([0, 0, 0, ..., 1, 1, 1], dtype=int32),
   array([2, 0, 0, ..., 0, 0, 3], dtype=int32),
   array([0, 0, 0, ..., 2, 2, 2], dtype=int32),
   array([9999,    1,    1, ..., 9999, 9999,    2], dtype=int32)]"""


    def _get_numerical_data(self, X):
        self.numberical_columns = X.select_dtypes(include=[np.number]).columns.tolist() # column name of numeric column
        num_data =X[self.numberical_columns].values
        return [num_data]

    def _create_model(self):
        categorical_input = []
        embedding_layers = []
        for idx, col in enumerate(self.catagorical_columns):
            Input(shape)




In [7]:
train_df = pd.read_csv("train.csv", low_memory=False)
test_df = pd.read_csv("test.csv", low_memory=False)
store_df = pd.read_csv("store.csv", low_memory=False)

train_data = pd.merge(train_df, store_df, how='inner', on='Store')
test_data = pd.merge(test_df, store_df, how='inner', on='Store')

In [8]:
X_train, y_train =train_data.drop(['Sales'],axis=1), train_data['Sales']
col_to_use = ['Store', 'Open', 'StoreType', 'DayOfWeek', 'Assortment', 'SchoolHoliday']
print(X_train[col_to_use].info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1017209 entries, 0 to 1017208
Data columns (total 6 columns):
 #   Column         Non-Null Count    Dtype 
---  ------         --------------    ----- 
 0   Store          1017209 non-null  int64 
 1   Open           1017209 non-null  int64 
 2   StoreType      1017209 non-null  object
 3   DayOfWeek      1017209 non-null  int64 
 4   Assortment     1017209 non-null  object
 5   SchoolHoliday  1017209 non-null  int64 
dtypes: int64(4), object(2)
memory usage: 46.6+ MB
None


In [20]:
cln = X_train.select_dtypes(include=[np.number]).columns.tolist()
X_train[cln].values.shape

(1017209, 12)